use ArteAtuarial2
select*from LOJA_VENDA

SELECT CASE WHEN VALOR_PAGO >200 THEN 'VALOR ALTO'
WHEN VALOR_PAGO > 100 AND VALOR_PAGO <= 200 THEN 'MÉDIO'
WHEN VALOR_PAGO < 100 THEN 'BAIXO'
END
FROM LOJA_VENDA
WHERE DATA_VENDA >='03-03-2017'

SELECT DISTINCT TOP 10 CODIGO_FILIAL, DATA_VENDA
FROM LOJA_VENDA 
WHERE MONTH(DATA_VENDA)=03 AND YEAR(DATA_VENDA)=2017
ORDER BY DATA_VENDA DESC




SELECT TOP 100 DISTINCT DATA_VENDA, VALOR_TOTAL,CODIGO_BARRA, CODIGO_FILIAL
FROM LOJA_VENDA_PRODUTO
WHERE VALOR_TOTAL >'55.50' ORDER BY VALOR_TOTAL ASC

SELECT*FROM LOJA_VENDA_TROCA WHERE QTDE >'2'

SELECT CODIGO_FILIAL, AVG(VALOR_PAGO) FROM LOJA_VENDA WHERE MONTH(DATA_VENDA)=03 GROUP BY CODIGO_FILIAL;
SELECT AVG(VALOR_PAGO) FROM LOJA_VENDA;

SELECT CODIGO_FILIAL, AVG(Distinct VALOR_PAGO) FROM LOJA_VENDA GROUP BY CODIGO_FILIAL


 SELECT COUNT(*) FROM LOJA_VENDA;
 SELECT DATA_VENDA, COUNT(*) FROM LOJA_VENDA GROUP BY DATA_VENDA;
 SELECT CPF_CGC_ECF, DATA_VENDA, COUNT(*) FROM LOJA_VENDA GROUP BY CPF_CGC_ECF, DATA_VENDA;
 SELECT CODIGO_FILIAL, COUNT(*) FROM LOJA_VENDA WHERE DATA_VENDA>= '2017-06-01 00 :00:00' GROUP BY CODIGO_FILIAL;

 SELECT CODIGO_FILIAL, MAX(VALOR_PAGO) FROM LOJA_VENDA WHERE DATA_VENDA='2017-03-02 00:00:00' GROUP BY CODIGO_FILIAL;

SELECT*FROM(
		SELECT MONTH(DATA_VENDA) AS MES,
		SUM(VALOR_PAGO) AS SOMA,
		ROUND(AVG(VALOR_PAGO),0) AS MEDIA,
		MAX(VALOR_PAGO) AS MAX,
		MIN(VALOR_PAGO) AS MIN,
		COUNT(*) AS CONTVENDAS,
		COUNT(DISTINCT DESCONTO) AS COUNTDESC,
		ROUND(SUM(VALOR_PAGO)/COUNT(*),0)*2 AS MEDIA2
		FROM LOJA_VENDA
		WHERE MONTH(DATA_VENDA)>=03 AND YEAR (DATA_VENDA)>=2017
		GROUP BY MONTH(DATA_VENDA)
		) AS SUB
		
		        
 SELECT * FROM LOJA_VENDA V 
 INNER JOIN FILIAIS F ON 
 F.COD_FILIAL=V.CODIGO_FILIAL 
 WHERE V.DATA_VENDA='2017-03-02';


SELECT TOP 10 * FROM LOJA_VENDA_PRODUTO
SELECT TOP 10 * FROM PRODUTOS

SELECT * FROM PRODUTOS P 
 INNER JOIN LOJA_VENDA_PRODUTO L ON
 L.PRODUTO=P.PRODUTO
  WHERE L.DATA_VENDA='03-02-2017';


 SELECT * FROM LOJA_VENDA V 
 JOIN LOJA_VENDA_PRODUTO LVP ON 
 LVP.TICKET=V.TICKET AND 
 LVP.DATA_VENDA=V.DATA_VENDA AND 
 V.CODIGO_FILIAL=LVP.CODIGO_FILIAL 
 JOIN PRODUTOS P ON
 LVP.PRODUTO=P.PRODUTO
 WHERE V.DATA_VENDA='03-02-2017';


SELECT * FROM LOJA_VENDA V 
LEFT JOIN LOJA_VENDA_TROCA LVT ON 
V.CODIGO_FILIAL=LVT.CODIGO_FILIAL 
AND V.TICKET=LVT.TICKET AND V.DATA_VENDA=LVT.DATA_VENDA 
--WHERE --LVT.DATA_VENDA='2017-03-02'
--LVT.DATA_VENDA IS NULL
WHERE V.DATA_VENDA='02-03-2017'



-- Crie uma consulta que exiba os 100 primeiros produtos_barra, sua coleção.


SELECT TOP 100 PB.CODIGO_BARRA,C.COLECAO FROM PRODUTOS_BARRA PB
LEFT JOIN PRODUTOS P ON
PB.PRODUTO=P.PRODUTO
LEFT JOIN COLECOES C ON
P.COLECAO= C.COLECAO


SELECT S3.SOMA03,S4.SOMA04,S3.SOMA03/S4.SOMA04 FROM(
      SELECT SUM (VALOR_PAGO)AS SOMA03
      FROM LOJA_VENDA
      WHERE MONTH (DATA_VENDA)=03 AND YEAR (DATA_VENDA)=2017) AS S3
      CROSS JOIN (SELECT SUM (VALOR_PAGO) AS SOMA04
      FROM LOJA_VENDA
      WHERE MONTH (DATA_VENDA)=04 AND YEAR (DATA_VENDA)=2017) AS S4


SELECT V.CODIGO_FILIAL 
FROM LOJA_VENDA V 
WHERE V.VALOR_PAGO= (SELECT AVG(VV.VALOR_PAGO) FROM LOJA_VENDA VV 
WHERE VV.DATA_VENDA>'2017-03-01') 

 




