CREATE DATABASE ESCOLA;
USE ESCOLA

CREATE TABLE PAISES(
ID INT NOT NULL IDENTITY PRIMARY KEY,
PAIS VARCHAR(100) NOT NULL,
CODIGOPAIS INT NULL,
SIGLA VARCHAR(5) NOT NULL
);

CREATE TABLE ESTADOS(
ID INT NOT NULL IDENTITY PRIMARY KEY,
ESTADO VARCHAR(100) NOT NULL,
PAISID INT NOT NULL FOREIGN KEY REFERENCES PAISES(ID),
SIGLA VARCHAR(2) NOT NULL
);

CREATE TABLE MUNICIPIOS(
ID INT NOT NULL IDENTITY PRIMARY KEY,
MUNICIPIO VARCHAR(100) NOT NULL,
ESTADOID INT NULL FOREIGN KEY REFERENCES ESTADOS(ID)
);

CREATE TABLE ENDEREÇO(
ID INT NOT NULL IDENTITY PRIMARY KEY,
LOGRADOURO VARCHAR(100) NOT NULL,
NUMERO VARCHAR(30) NOT NULL,
COMPLEMENTO VARCHAR(50) NOT NULL,
CEP VARCHAR(8) NULL,
MUNICIPIOID INT NULL FOREIGN KEY REFERENCES MUNICIPIOS(ID)
);

CREATE TABLE ALUNOS(
ID INT NOT NULL IDENTITY PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
CPF VARCHAR(11) NULL,
SEXO CHAR NOT NULL,
ATIVO TINYINT NOT NULL,
ENDEREÇOID INT NULL FOREIGN KEY REFERENCES ENDEREÇO(ID)
);

CREATE TABLE PROFESSORES(
ID INT NOT NULL IDENTITY PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
CPF VARCHAR(11),
SEXO CHAR NOT NULL,
ATIVO TINYINT NOT NULL,
ENDEREÇOID INT NOT NULL FOREIGN KEY REFERENCES ENDEREÇO(ID)
);

CREATE TABLE DISCIPLINAS(
ID INT NOT NULL IDENTITY PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DATANASCIMENTO DATE NOT NULL,
CARGAHORARIA INT NOT NULL,
ATIVO TINYINT NOT NULL,
DATACRIAÇAO DATE
);


CREATE TABLE TURMAS(
ID INT NOT NULL IDENTITY PRIMARY KEY,
HORARIO VARCHAR(10) NOT NULL,
SALA INT NOT NULL,
DISCIPLINASID INT NOT NULL FOREIGN KEY REFERENCES DISCIPLINAS(ID),
PROFESSORESID INT NOT NULL FOREIGN KEY REFERENCES PROFESSORES(ID)
);

CREATE TABLE TURMA_ALUNOS(
ID INT NOT NULL IDENTITY PRIMARY KEY,
NOTA FLOAT NULL,
FALTAS INT NULL,
TURMASID INT NOT NULL FOREIGN KEY REFERENCES TURMAS(ID),
ALUNOSID INT NULL FOREIGN KEY REFERENCES ALUNOS(ID)
);


ALTER TABLE MUNICIPIOS ADD CODIGOIBGE VARCHAR(10) NULL;
ALTER TABLE PROFESSORES DROP COLUMN SEXO; 

ALTER TABLE PROFESSORES ALTER COLUMN NOME VARCHAR(150) NOT NULL;

DROP TABLE TURMA_ALUNOS
DROP TABLE TURMAS
DROP TABLE DISCIPLINAS
DROP TABLE PROFESSORES
DROP TABLE ALUNOS
DROP TABLE ENDEREÇO
DROP TABLE MUNICIPIOS
DROP TABLE ESTADOS
DROP TABLE PAISES